general:
  description: Config for accessing DWD (Deutscher Wetterdienst) ICON-EU NWP data
  name: PVNet current (DWD)
  destination_platform: "huggingface"
  destination_dataset_id: "openclimatefix/dwd-icon-eu-deterministic-solar"  

input_data:
  default_forecast_minutes: 480
  default_history_minutes: 120
  nwp:
    dwd:
      dropout_fraction: 1.0
      dropout_timedeltas_minutes:
        - -360
      forecast_minutes: 480.0
      history_minutes: 120
      max_staleness_minutes: null
      s3_bucket: "https://opendata.dwd.de/weather/nwp/"  
      s3_prefix: "icon-eu/grib"  
      local_output_dir: "/absolute/path/to/dwd"  
      nwp_accum_channels:
        - ASWDIFD_S  # Diffuse downward shortwave radiation at surface
        - ASWDIR_S   # Direct shortwave radiation at surface
        - ATHB_S     # Net budget of radiation at surface
      nwp_channels:
        - T_2M       # 2m temperature
        - ASWDIFD_S  # Diffuse downward shortwave radiation at surface
        - ASWDIR_S   # Direct shortwave radiation at surface
        - ATHB_S     # Net budget of radiation at surface
        - CLCH       # High cloud cover
        - CLCM       # Medium cloud cover
        - CLCL       # Low cloud cover
        - CLCT       # Total cloud cover
        - H_SNOW     # Snow depth
        - Z0         # Surface roughness length
        - VMAX_10M   # Maximum wind speed at 10m
        - DD_10M     # Wind direction at 10m
      nwp_image_size_pixels_height: 1097  # ICON-EU grid dimensions
      nwp_image_size_pixels_width: 657
      nwp_provider: dwd
      nwp_zarr_path: "/data/dwd/dwd_data.zarr"  
      time_resolution_minutes: 60

